[book]
authors = ["Gaute Hope"]
language = "en"
multilingual = false
src = "src"
title = "vim-tmux-python-git setup"

[output.html]
git-repository-url = "https://github.com/gauteh/vim-tmux-py-tutorial"

